### ISSUE TITLE
can't put in Infinity Capacitor

### ISSUE THREAD

**Issue by Leftorius** [Tfarcenim/avaritiaio#1]
I can't put it in any machine?

EnderIO 5.0.39
Avaritia IO 1.1

**Comment by Tfarcenim** [comment]
Looking into that, will be permanently fixed by the next update.

**Comment by MSandro** [comment]
same here 5.0.40 and Avaritia 3.3.0 Avaritia IO 1.2
👎

**Comment by Tfarcenim** [comment]
This issue is now fixed in 1.3
