### ISSUE TITLE
Duplicate EnderIO files

### ISSUE THREAD

**Issue by GhEppIO82** [Tfarcenim/avaritiaio#2]
bro install your mod via twich duplicate files of EnderIO

**Comment by Trip-kun** [comment]
What in the world does this mean. He doesn't install the mod, you do. What does duplicate enderIO files really have to do with this? Use either the modular enderIO installation or the full one, not both

**Comment by Tfarcenim** [comment]
the mod doesn't ship any extra ender io files at all so duplicates shouldn't be an issue
